config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#home'

  get 'about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  before_save { self.email = email.downcase }
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})/i
  validates :email, presence: true, length: { maximum:105 }, uniqueness: { case_sensitive: false}, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:edit, :update, :show, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 3)
  end

  def new
    @article = Article.new
  end

  def edit
    
  end

  def create
    debugger
    @article = Article.new(article_params)
    @article.user =
    if @article.save
      flash[:success] = "Article was Successfully Created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    
    if @article.update(article_params)
      flash[:success] = "Article was Successfully Updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show
    
  end

  def destroy
    @article.destroy
    flash[:danger] = "Article Deleted Successfully"
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

  end

  def about

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have Successfully Logged In"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something wrong with your login information"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have Logged Out Successfully"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.paginate(page: params[:page], per_page: 3)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the BlogsNow #{@user.username}"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
     @user = User.find(params[:id])
     if @user.update(user_params)
      flash[:success] = "Your Account was updated Successfully"
      redirect_to articles_path
     else
      render 'edit'
     end  
  end

  def show
    @user = User.find(params[:id])
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 3)
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password)      
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80} )
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded-circle mx-auto")
  end
end

app/views/articles/_article.html.erb
<% obj.each do |a| %>
  <br>
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <div class="card card-inverse" style="background-color: #C8C2C1">
        <div class="card-block" style="margin: 20px">
          <div class="article-title">
            <%= link_to a.title, article_path(a) %>
          </div>
          <div class="article-body">
            <%= truncate(a.description, length: 150) %>
            <div class="article-meta-details">
              <small>Created By: <%= a.user.username if a.user %>, <%= time_ago_in_words(a.created_at) %> ago, Last Updated: <%= time_ago_in_words(a.updated_at) %> ago</small>
            </div>
          </div>
          <div class="article-actions">
            <%= link_to 'Edit this Article', edit_article_path(a), method: "get", class:"btn btn-md btn-primary" %>
            <%= link_to 'Delete this Article', article_path(a), method: :delete, data: { confirm: "Are You Sure you want to DELETE the Article?"}, class:"btn btn-md btn-danger" %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<br>
<div class='row'>
  <div class='col-md-12'>
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group row">
        <div class="col-form-label col-sm-2">
          <%= f.label :title %>
        </div>
      
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of Article", autofocus: true %>
        </div>
      </div>
      
      <div class="form-group row">
        <div class="col-form-label col-sm-2">
          <%= f.label :description %>
        </div>
      
        <div class="col-sm-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of Article" %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-sm-12 offset-sm-2">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
    <% end %>

    <div class="col-md-5 offset-md-4">
      { <%= link_to 'Cancel Requet and Return to Article Listing', articles_path, method: "get" %> }
    </div>
  </div>  
</div>

app/views/articles/edit.html.erb
<br>
<h1 align="center">Edit existing Article</h1>
<br>
<%= render 'form' %>

app/views/articles/index.html.erb
<br>
<h1 align="center">Listing All Articles</h1>

<br>
<div class="pagination justify-content-center">
  <%= will_paginate %>
</div>

<%= render 'article', obj: @articles %>

<div class="pagination justify-content-center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<br>
<h1 align="center">Create an Article</h1>
<br>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">TITLE: <%= @article.title%></h2>

<br>

<div class="col-md-10 offset-md-1">
  <div class="card card-inverse" style="background-color: #C8C2C1">
    <div class="card-block" style="margin: 20px">
      <ul class="listing">
        <div align="center">
          <div class="card-block" style="margin: 2px">
            <li>Created By:</li>
            <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
            <li class="card-title"><%= link_to @article.user.username, user_path(@article.user) %></li>
            <li class="card-text"><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
          </div>
        </div>
      </ul>
      <hr style="background-color: #E3623F; height: 1px" >
      <h4 align="center" class="center card-title"><strong><p>DESCRIPTION</p></strong></h4>
      <hr style="background-color: #E3623F; height: 1px">
      <p class="card-text"><%= simple_format(@article.description) %></p>
      <br>
      <div class="article-actions">
        <%= link_to 'Edit this Article', edit_article_path(@article), method: "get", class:"btn btn-md btn-primary" %>
         <%= link_to 'Delete this Article', article_path(@article), method: :delete, data: { confirm: "Are You Sure you want to DELETE the Article?"}, class:"btn btn-md btn-danger" %>
        <%= link_to 'View all Articles', articles_path, method: "get", class:"btn btn-md btn-success" %>
      </div>
    </div>
  </div>
</div>

<br>


app/views/layouts/_footer.html.erb
<div class="container">
  <footer>
    <small>
      Copyright&copy; <a href= "gaurishshaw@gmail.com">Shaw Industries</a>
      by <a href="gaurishshaw@gmail.com">Gaurish Kumar Shaw </a>
    </small>
    <nav>
      <ul>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<br>
<div class="row">
  <div class="col-md-10 offset-md-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%= "#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #FF8300;">
  
  <%= link_to "BlogsNow", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Articles", articles_path, {:class => "nav-link"} %>
      </li>
      <li class="nav-item nav-link">
        <%= link_to 'Log Out', logout_path, method: :delete %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Actions
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "New Article", new_article_path, {:class => "dropdown-item"} %>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogsNow</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <p>
      <%= debug(params) if Rails.env.development? %>
    </p>
  </body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<HTML>

  <HEAD>
  </HEAD>

  <BODY>
    
    <h1 style="text-align:center;">
      This is The About Page For the Blog Application
    </h1>
    <br>
    <br>
    <%= link_to 'Home', root_path %> |
    
    
    
  </BODY> 

</HTML>

app/views/pages/home.html.erb
<br>
<div class="center jumbotron">
  <h1>BLOGSNOW</h1>
  <br>
  <br>
  <%= link_to 'Sign Up', "#", class: "btn btn-danger btn-lg btn-xlarge" %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="card card-danger card-inverse">
        <div class="card-header">
          <h3 class="card-title">
            <%= pluralize(obj.errors.count, "error") %>
            Prohibited this Article from being Saved!
          </h3>
          <div class="card-block">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<br>
<div class='row'>
  <div class='col-md-12'>
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group row">
        <div class="col-form-label col-sm-2">
          <%= f.label :Username %>
        </div>
      
        <div class="col-sm-8">
          <%= f.text_field :username, class: "form-control", placeholder: "Enter Username", autofocus: true %>
        </div>
      </div>
      
      <div class="form-group row">
        <div class="col-form-label col-sm-2">
          <%= f.label :Email %>
        </div>
      
        <div class="col-sm-8">
          <%= f.email_field :email, class: "form-control", placeholder: "Enter Email" %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-form-label col-sm-2">
          <%= f.label :Password %>
        </div>
      
        <div class="col-sm-8">
          <%= f.password_field :password, class: "form-control", placeholder: "Enter Password" %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-sm-12 offset-sm-2">
          <%= f.submit(@user.new_record? ? "Sign-Up" : "Update Account", class: 'btn btn-primary btn-lg') %>
        </div>
      </div>
    <% end %>

    <div class="col-md-5 offset-md-4">
      { <%= link_to 'Cancel Requet and Return to Article Listing', articles_path, method: "get" %> }
    </div>
  </div>  
</div>

app/views/users/edit.html.erb
<strong><h1 align="center"> Edit Your Account </h1></strong>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All Bloggers</h1>
<br>
<div align="center">
  <div class="pagination justify-content-center">
    <%= will_paginate %>
  </div>
  <% @users.each do |u| %>
    <ul class="listing">
      <div class="row">
        <div class="col-md-4 offset-md-4">
          <div class="card card-inverse" style="background-color: #C8C2C1; padding: 10px">
            <div class="card-block" style="margin: 2px">
              <li><%= link_to gravatar_for(u), user_path(u) %></li>
              <li class="card-title"><%= link_to u.username, user_path(u) %></li>
              <li class="card-body"><small><%= pluralize(u.articles.count, "article") if u.articles %></small></li>
            </div>
          </div>
        </div>
      </div>
    </ul>
    <br>
  <% end %>
  <div class="pagination justify-content-center">
    <%= will_paginate %>
  </div>
</div>

app/views/users/new.html.erb
<strong><h1 align="center"> Sign-Up </h1></strong>

<%= render 'form' %>

app/views/users/show.html.erb
<strong><h1 align="center">Welcome <%= @user.username %> to Your Page </h1></strong>
<br>
<div class="row">
  <div class="col-md-4 offset-md-4 center">
    <%= gravatar_for @user, size: 150 %>
  </div>
</div>
<br>
<h4 align="center"><%= @user.username %>'s Articles</h4>

<div class="pagination justify-content-center">
    <%= will_paginate @user_articles %>
</div>

<%= render 'articles/article', obj: @user_articles %>

<div class="pagination justify-content-center">
    <%= will_paginate @user_articles %>
</div>